In [1]:
import import_ipynb
import os
import pandas as pd
from WNDomains import WordNetDomains 
wnd = WordNetDomains(wordnet_home='/Users/valeriaguttilla/Desktop/MASTER/PROGETTONE/ANALISI_TESTUALE/ANALISI TRAME/WordNet')

importing Jupyter notebook from WNDomains.ipynb

In [55]:
path= r"/Users/valeriaguttilla/Desktop/MASTER/PROGETTONE/ANALISI_TESTUALE/ANALISI TRAME/TRAME/ANIMATED"

#domains_trama = set()  


list1=[1990, 2000, 2010]
dict_all_domains={}

for dirpath, dirnames, files in os.walk(path):
    print(f'Found directory: {dirpath}')

    dict_domains = {}
    for file in files:
        if file[0] == '.':
            continue

        domains_trama_all = set()

        with open(dirpath+ "/" + file, 'r', encoding='Latin-1') as f:
            text=f.read()
            words = text.split()

            file=file.split('.')[0]
            decade=dirpath.split('/')[-1]

            for word in words:
               # domains_trama|=(wnd.get_domains(word, 'n', first_sense_only=True))   ---- da usare per solo i nomi
                domains_trama_all |= (wnd.get_domains(word, 'n', first_sense_only=True))
                domains_trama.discard('set()')



            for domain in domains_trama_all:
                if domain in dict_domains:
                    dict_domains[domain].append(file)
                else:
                    dict_domains[domain] = [file]

    for d in dict_domains:
        if decade in list1:
            if len(dict_domains[d]) >= (len(files)/2):
                if d in dict_all_domains:
                    dict_all_domains[d].append(decade)
                else:
                    dict_all_domains[d] = [decade]
        else:
            if len(dict_domains[d]) >= (len(files)*(0.25)):
                if d in dict_all_domains:
                    dict_all_domains[d].append(decade)
                else:
                    dict_all_domains[d] = [decade]

Found directory: /Users/valeriaguttilla/Desktop/MASTER/PROGETTONE/ANALISI_TESTUALE/ANALISI TRAME/TRAME/ANIMATED
Found directory: /Users/valeriaguttilla/Desktop/MASTER/PROGETTONE/ANALISI_TESTUALE/ANALISI TRAME/TRAME/ANIMATED/1980
Found directory: /Users/valeriaguttilla/Desktop/MASTER/PROGETTONE/ANALISI_TESTUALE/ANALISI TRAME/TRAME/ANIMATED/1960
Found directory: /Users/valeriaguttilla/Desktop/MASTER/PROGETTONE/ANALISI_TESTUALE/ANALISI TRAME/TRAME/ANIMATED/1950
Found directory: /Users/valeriaguttilla/Desktop/MASTER/PROGETTONE/ANALISI_TESTUALE/ANALISI TRAME/TRAME/ANIMATED/2000
Found directory: /Users/valeriaguttilla/Desktop/MASTER/PROGETTONE/ANALISI_TESTUALE/ANALISI TRAME/TRAME/ANIMATED/2010
Found directory: /Users/valeriaguttilla/Desktop/MASTER/PROGETTONE/ANALISI_TESTUALE/ANALISI TRAME/TRAME/ANIMATED/1940
Found directory: /Users/valeriaguttilla/Desktop/MASTER/PROGETTONE/ANALISI_TESTUALE/ANALISI TRAME/TRAME/ANIMATED/1970
Found directory: /Users/valeriaguttilla/Desktop/MASTER/PROGETTONE/ANALISI_TESTUALE/ANALISI TRAME/TRAME/ANIMATED/1990
Found directory: /Users/valeriaguttilla/Desktop/MASTER/PROGETTONE/ANALISI_TESTUALE/ANALISI TRAME/TRAME/ANIMATED/1930

In [191]:
dict_all_domains

{'tourism': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'plants': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'town_planning': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'economy': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'military': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'agriculture': ['1980', '1950'],
 'baseball': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'person': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'psychology': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1970',
  '1990',
  '1930'],
 'geology': ['1980', '1960', '1950', '2000', '2010', '1970', '1990', '1930'],
 'medicine': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'money': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'cricket': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'acoustics': ['1980', '1950'],
 'religion': ['1980', '1960', '1950', '2000', '2010', '1970', '1990', '1930'],
 'anatomy': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'time_period': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'factotum': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'law': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'art': ['1980', '1960', '2000', '2010', '1970', '1990'],
 'heraldry': ['1980', '1950', '2010', '1970', '1930'],
 'geography': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'chemistry': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'administration': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'exchange': ['1980', '1960', '2000', '2010', '1970', '1990', '1930'],
 'metrology': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'betting': ['1980'],
 'telecommunication': ['1980',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'animals': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'psychological_features': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'politics': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'history': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'music': ['1980', '1960', '1950', '2000', '2010', '1970', '1990', '1930'],
 'food': ['1980', '2000', '2010', '1940', '1970', '1930'],
 'commerce': ['1980', '1960', '1950', '2000', '2010', '1970', '1990', '1930'],
 'nautical': ['1980', '1960', '1950', '2000', '2010', '1970', '1990'],
 'number': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'astronomy': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'sociology': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'university': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'biology': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'entomology': ['1980', '1950', '2010', '1970', '1990', '1930'],
 'sport': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'physics': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'transport': ['1980', '1960', '1950', '2000', '2010', '1940', '1970', '1990'],
 'color': ['1980', '1960', '1950', '2000', '1940', '1970'],
 'industry': ['1980', '1960', '1950', '2000', '2010', '1990'],
 'racing': ['1980', '1950', '2000', '2010', '1970', '1930'],
 'mathematics': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990'],
 'hunting': ['1980', '1970', '1930'],
 'school': ['1980', '1960', '2000', '2010'],
 'furniture': ['1980', '1960', '1950', '2000', '2010', '1990', '1930'],
 'sexuality': ['1980'],
 'linguistics': ['1980', '1960', '2000', '2010', '1970', '1990'],
 'finance': ['1980', '1950', '2000', '1970', '1990', '1930'],
 'free_time': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'fashion': ['1980', '1960', '1950', '2000', '2010', '1970', '1990'],
 'literature': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1940',
  '1970',
  '1990',
  '1930'],
 'gastronomy': ['1980',
  '1960',
  '1950',
  '2000',
  '2010',
  '1970',
  '1990',
  '1930'],
 'buildings': ['1980', '1960', '1950', '2000', '2010', '1970', '1990', '1930'],
 'play': ['1980', '1960', '1950', '2000', '2010', '1970', '1990'],
 'theatre': ['1960', '1950', '2000', '2010', '1940', '1970', '1990', '1930'],
 'mechanics': ['1960', '2000', '2010', '1970', '1990'],
 'anthropology': ['1960', '1950', '2000', '2010', '1970', '1990', '1930'],
 'electricity': ['1960', '2010', '1930'],
 'tax': ['1960', '1950', '2000', '2010', '1940', '1970', '1990', '1930'],
 'electronics': ['1960', '2000', '2010', '1990'],
 'photography': ['1960', '2000', '2010', '1940', '1990', '1930'],
 'meteorology': ['1960', '2000', '2010', '1990', '1930'],
 'archery': ['1960', '1950', '2000', '2010', '1970', '1990'],
 'electrotechnology': ['1960', '2000', '2010', '1990'],
 'grammar': ['1960'],
 'computer_science': ['1960', '2010'],
 'football': ['1960', '1950'],
 'jewellery': ['1960', '1970', '1990', '1930'],
 'publishing': ['1960', '1950', '2000', '2010', '1970', '1990', '1930'],
 'mythology': ['1960', '1950', '1970', '1990'],
 'pedagogy': ['1960', '2010'],
 'occultism': ['1960'],
 'painting': ['1960', '1970'],
 'swimming': ['1960', '1970'],
 'physiology': ['1950', '2000', '2010', '1970', '1990', '1930'],
 'vehicles': ['1950'],
 'post': ['1950', '2000'],
 'telephony': ['2000', '2010', '1970'],
 'enterprise': ['2000', '2010', '1970'],
 'telegraphy': ['1970'],
 'geometry': ['1970'],
 'atomic_physic': ['1970'],
 'earth': ['1970'],
 'optics': ['1970'],
 'golf': ['1970'],
 'philosophy': ['1970'],
 'hydraulics': ['1970'],
 'card': ['1990'],
 'health': ['1930']}

In [194]:
df= pd.DataFrame(dict([(k,pd.Series(v)) for k,v in dict_all_domains.items() ]))
len(df.columns.unique())

96

In [195]:
df

,tourism,plants,town_planning,economy,military,agriculture,baseball,person,psychology,geology,...,telegraphy,geometry,atomic_physic,earth,optics,golf,philosophy,hydraulics,card,health
0,1980,1980,1980,1980,1980,1980,1980,1980,1980,1980,...,1970,1970,1970,1970,1970,1970,1970,1970,1990,1930
1,1960,1960,1960,1960,1960,1950,1960,1960,1960,1960,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1950,1950,1950,1950,1950,NaN,1950,1950,1950,1950,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000,2000,2000,2000,2000,NaN,2000,2000,2000,2000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010,2010,2010,2010,2010,NaN,2010,2010,2010,2010,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1940,1940,1940,1940,1940,NaN,1940,1940,1970,1970,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1970,1970,1970,1970,1970,NaN,1970,1970,1990,1990,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1990,1990,1990,1990,1990,NaN,1990,1990,1930,1930,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1930,1930,1930,1930,1930,NaN,1930,1930,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [190]:
# DA NON FARE ANDARE
#tentativo inutile e cmq non riuscito cmq di ordinare per anno
df=df.fillna(0)
columns=list(df.columns)

for column in columns:
    year = 1930
    for j in range (0, 9):
        if df.iloc[j, df.columns.get_loc(column)] == 0:
            year+=1
            continue
        df.iloc[j, df.columns.get_loc(column)] = year
        year += 10

In [196]:
df_null = df.isnull().sum(axis = 0)
df_null=df_null.to_frame().reset_index()

In [197]:
df_null.rename(columns={'index': 'domain', 0:'counts'}, inplace=True)
df_null

           domain  counts
0         tourism       0
1          plants       0
2   town_planning       0
3         economy       0
4        military       0
..            ...     ...
91           golf       8
92     philosophy       8
93     hydraulics       8
94           card       8
95         health       8

[96 rows x 2 columns]

In [198]:
# se uno vuol fare dei check sui valori nulli (ossia )
for g in range (0,95):
    if df_null['counts'][g] > 5:
        print(df_null['domain'][g])

agriculture
acoustics
betting
hunting
sexuality
electricity
grammar
computer_science
football
pedagogy
occultism
painting
swimming
vehicles
post
telephony
enterprise
telegraphy
geometry
atomic_physic
earth
optics
golf
philosophy
hydraulics
card

In [199]:
df.to_csv(r"/Users/valeriaguttilla/Desktop/MASTER/PROGETTONE/ANALISI_TESTUALE/ANALISI TRAME/TRAME/ANIMATED/csv_trame.csv")